"""add param to userItem

Revision ID: 02a72dfb57c4
Revises: a1e8679cd010
Create Date: 2024-01-22 17:44:44.879668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a72dfb57c4'
down_revision: Union[str, None] = 'a1e8679cd010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('active', sa.Boolean(), nullable=False, server_default=str(True)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_items', 'active')
    # ### end Alembic commands ###
