"""add item params

Revision ID: 0702a8d1e945
Revises: 8c10e0977dc9
Create Date: 2024-01-20 11:48:29.048341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0702a8d1e945'
down_revision: Union[str, None] = '8c10e0977dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    items = sa.sql.table('items', sa.Column('cost_in_rubles', sa.NUMERIC()))
    op.execute(
        items.update()
        .where(items.c.cost_in_rubles.is_(None))
        .values(cost_in_rubles=0)
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'cost_in_rubles',
                    existing_type=sa.NUMERIC(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'cost_in_rubles',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
