"""moogold

Revision ID: 0aa8615fbf01
Revises: 1252df1c4f6a
Create Date: 2023-12-12 18:20:14.755290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0aa8615fbf01"
down_revision: Union[str, None] = "1252df1c4f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items_findings", sa.Column("moogoald_order_id", sa.String(), nullable=True)
    )
    op.add_column("items_findings", sa.Column("total", sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items_findings", "total")
    op.drop_column("items_findings", "moogoald_order_id")
    # ### end Alembic commands ###
