"""add columns

Revision ID: 0ca1bbe6c139
Revises: 0396f003ccf4
Create Date: 2024-01-23 17:30:37.156373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ca1bbe6c139"
down_revision: Union[str, None] = "0396f003ccf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promo_codes", sa.Column("name", sa.String(), nullable=False))
    op.add_column(
        "promo_codes", sa.Column("creation_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promo_codes", "creation_date")
    op.drop_column("promo_codes", "name")
    # ### end Alembic commands ###
