"""itemsf

Revision ID: 1252df1c4f6a
Revises: a32a78fe82fc
Create Date: 2023-12-07 19:34:54.715869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1252df1c4f6a"
down_revision: Union[str, None] = "a32a78fe82fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items_findings_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ext_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ext_id"),
    )
    op.create_table(
        "items_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("itemfs_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("item_id", sa.String(), nullable=True),
        sa.Column("genshin_user_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["items_findings_status.ext_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("itemfs_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items_findings")
    op.drop_table("items_findings_status")
    # ### end Alembic commands ###
