"""empty message

Revision ID: 3420f3b3adbd
Revises: e05de2d4cae4
Create Date: 2023-11-06 15:37:58.793208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3420f3b3adbd'
down_revision: Union[str, None] = 'e05de2d4cae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cost_in_rubles', sa.DECIMAL(), nullable=True))
    op.alter_column('items', 'cost',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'cost',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('items', 'cost_in_rubles')
    # ### end Alembic commands ###
