"""add new field

Revision ID: 37f911ae641a
Revises: e4e42a9ed014
Create Date: 2024-01-24 18:00:04.231625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37f911ae641a"
down_revision: Union[str, None] = "e4e42a9ed014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("translit_name", sa.String()))
    # ### end Alembic commands ###

    cases = sa.sql.table(
        "cases", sa.Column("translit_name", sa.String()), sa.Column("name", sa.String())
    )
    op.execute(
        cases.update()
        .where(cases.c.translit_name.is_(None))
        .values(translit_name=cases.c.name)
    )
    op.alter_column("cases", "translit_name", existing_type=sa.String(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "translit_name")
    # ### end Alembic commands ###
