"""add default

Revision ID: 3839b29f39b0
Revises: 3f4149096298
Create Date: 2024-01-23 23:16:30.631800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3839b29f39b0'
down_revision: Union[str, None] = '3f4149096298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'activations',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'activations',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
