"""empty message

Revision ID: 3d38087a7e1c
Revises: d9aa188577db
Create Date: 2023-11-09 17:48:35.493932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d38087a7e1c"
down_revision: Union[str, None] = "d9aa188577db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("rarity_id", sa.String(), nullable=True))
    op.drop_constraint("items_rarity_category_id_fkey", "items", type_="foreignkey")
    op.create_foreign_key(None, "items", "rarity_category", ["rarity_id"], ["ext_id"])
    op.drop_column("items", "rarity_category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "rarity_category_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "items", type_="foreignkey")
    op.create_foreign_key(
        "items_rarity_category_id_fkey",
        "items",
        "rarity_category",
        ["rarity_category_id"],
        ["category_id"],
    )
    op.drop_column("items", "rarity_id")
    # ### end Alembic commands ###
