"""add id_gen

Revision ID: 3dcd8231cb23
Revises: 8acc3b06623c
Create Date: 2024-01-25 17:30:59.401203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3dcd8231cb23"
down_revision: Union[str, None] = "8acc3b06623c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calcs", sa.Column("calc_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "calcs", ["calc_id"])
    op.add_column("promo_codes", sa.Column("promo_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "promo_codes", ["promo_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "promo_codes", type_="unique")
    op.drop_column("promo_codes", "promo_id")
    op.drop_constraint(None, "calcs", type_="unique")
    op.drop_column("calcs", "calc_id")
    # ### end Alembic commands ###
