"""add limit activation

Revision ID: 3f4149096298
Revises: 438651783295
Create Date: 2024-01-23 22:08:31.460284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4149096298'
down_revision: Union[str, None] = '438651783295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('limit_activations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'limit_activations')
    # ### end Alembic commands ###
