"""add summ

Revision ID: 438651783295
Revises: dc4c9306e6e4
Create Date: 2024-01-23 20:16:33.471540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "438651783295"
down_revision: Union[str, None] = "dc4c9306e6e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promo_codes",
        sa.Column("summ", sa.DECIMAL(), nullable=False, server_default=str(1)),
    )
    # ### end Alembic commands ###
    op.alter_column("promo_codes", "summ", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promo_codes", "summ")
    # ### end Alembic commands ###
