"""add Unicue field

Revision ID: 44849121c238
Revises: 37f911ae641a
Create Date: 2024-01-25 14:40:57.468291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44849121c238"
down_revision: Union[str, None] = "37f911ae641a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cases", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "cases", ["name"])
    op.create_unique_constraint(None, "cases", ["translit_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cases", type_="unique")
    op.drop_constraint(None, "cases", type_="unique")
    op.alter_column("cases", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
