"""add active field cases 

Revision ID: 58ee438c2271
Revises: 32a71fd45f6e
Create Date: 2024-01-28 11:20:04.233829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58ee438c2271"
down_revision: Union[str, None] = "32a71fd45f6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases",
        sa.Column("active", sa.Boolean(), server_default="True", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "active")
    # ### end Alembic commands ###
