"""moogold_order

Revision ID: 760b58596bcb
Revises: 0aa8615fbf01
Create Date: 2023-12-12 19:03:40.832219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760b58596bcb'
down_revision: Union[str, None] = '0aa8615fbf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_moogold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itemfs_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['itemfs_id'], ['items_findings.itemfs_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_moogold')
    # ### end Alembic commands ###
