"""add calc table

Revision ID: 798e3d6084f0
Revises: 02a72dfb57c4
Create Date: 2024-01-23 16:33:12.142276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798e3d6084f0'
down_revision: Union[str, None] = '02a72dfb57c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summ', sa.DECIMAL(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calcs')
    # ### end Alembic commands ###
