"""empty message

Revision ID: 7a24b37303c2
Revises: da4ce35f8db5
Create Date: 2023-11-06 17:28:27.129171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a24b37303c2'
down_revision: Union[str, None] = 'da4ce35f8db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('individual_percent', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'individual_percent')
    # ### end Alembic commands ###
