"""add case pricr 

Revision ID: 8acc3b06623c
Revises: 44849121c238
Create Date: 2024-01-25 16:43:17.870178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8acc3b06623c"
down_revision: Union[str, None] = "44849121c238"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases", sa.Column("price", sa.DECIMAL(), nullable=False, server_default=str(0))
    )
    # ### end Alembic commands ###
    op.alter_column("cases", "price", existing_type=sa.DECIMAL(), server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "price")
    # ### end Alembic commands ###
