"""add item params

Revision ID: 8c10e0977dc9
Revises: 27b40b2210a4
Create Date: 2024-01-20 03:11:46.169370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c10e0977dc9"
down_revision: Union[str, None] = "27b40b2210a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column("sale", sa.Boolean(), nullable=False, server_default=str(True)),
    )
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("items", "sale")
    # ### end Alembic commands ###
