"""create o2m relationship

Revision ID: cb6ad08d0e36
Revises: 55c292560c9a
Create Date: 2024-01-19 23:41:43.170047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb6ad08d0e36"
down_revision: Union[str, None] = "55c292560c9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "rarity_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "rarity_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
