"""empty message

Revision ID: db674d5494d2
Revises: 1dce0637dad1
Create Date: 2023-11-08 21:41:32.622284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db674d5494d2'
down_revision: Union[str, None] = '1dce0637dad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_rarity_category_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'rarity_category', ['rarity_category_id'], ['ext_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_rarity_category_id_fkey', 'items', 'rarity_category', ['rarity_category_id'], ['category_id'])
    # ### end Alembic commands ###
