"""add code_data

Revision ID: dc4c9306e6e4
Revises: 0ca1bbe6c139
Create Date: 2024-01-23 18:27:34.066711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4c9306e6e4'
down_revision: Union[str, None] = '0ca1bbe6c139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('code_data', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'promo_codes', ['code_data'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_codes', type_='unique')
    op.drop_column('promo_codes', 'code_data')
    # ### end Alembic commands ###
