"""empty message

Revision ID: e52a3a68704a
Revises: 24ebffd23b03
Create Date: 2023-11-10 22:53:32.536891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a3a68704a'
down_revision: Union[str, None] = '24ebffd23b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rarity_category', 'category_percent',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rarity_category', 'category_percent',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
